### ISSUE TITLE
When an attribute is reused (nested syntax), the header line breadcrumb path is only correct for the first occurrence

### ISSUE THREAD

**Issue by sir4ur0n** [oxalica/nil#107]
The title is probably unclear, I wasn't sure how to describe it.

Let's use an example:
```nix
{
  a = "a";
  b = {
    c.d = true;
    c.e = "boom!";
  };
}
```

By "header line breadcrumb" I refer to this:
![image](https://github.com/oxalica/nil/assets/1204125/fafabd3f-618d-497b-9045-3f056a5900ad)

* :heavy_check_mark: When putting my cursor on `a`, the breadcrumb is `a`
* :heavy_check_mark: When putting my cursor on `b`, the breadcrumb is `b`
* :heavy_check_mark: When putting my cursor on the first `c`, the breadcrumb is `b > c > d`
* :heavy_check_mark: When putting my cursor on `d`, the breadcrumb is `b > c > d`
* :boom: When putting my cursor on the second `c`, the breadcrumb is `b`
* :boom: When putting my cursor on `e`, the breadcrumb is `b`

I think that putting the cursor on the second `c` or on `e` should display the breadcrumb `b > c > e`.

Note that if we inverse `c.d` and `c.e`, the problem now appears for `c.d`, so I feel like the breadcrumb is only correct for the first occurrence of a nested attribute.

* `nil --version`: `nil 2023-08-09`
* `emacs --version`: `GNU Emacs 29.1`
* Emacs packages:
  * `lsp-mode`: `lsp-mode-20230914.1237`
  * `lsp-ui`: `lsp-ui-20230811.552`

**Comment by oxalica** [comment]
The problem here is that Nix allows an attribute to be defined in multiple places but semantically merge them, and we currently print the symbol tree semantically (with attributes merged). Consider this case:

```nix
{
  a.b = 1;
  d = 2;
  a.c = 3;
}
```

Then the current symbol tree is:
```
|- a (covers ???)
|  |- b (covers "b = 1;")
|  \- c (covers "c = 3;")
\- d (covers "d = 2;")
```

If the covering range (`range` in LSP spec) of `a` is the first line `a.b = 1;`, then the client will not show properly when the cursor is on `a.c`, because `c` is outside the range of its parent. If its covering all 3 lines inside, then `d` will not be shown properly either, because its unexpectedly inside another node.

I think the only way is to split the tree to be syntactical, only possibly merge adjacent ones.
```
|- a (covers "a.b = 1";)
|  \- b (covers "b = 1;")
|- d (covers "d = 2;")
|- a (covers "a.c = 3";)
   \- c (covers "c = 3;")
```

This will give the correct breadcrumb, but make the symbol tree more complex and hard to find everything under `a` in one shot. As a reference, likewise, `impl` blocks in Rust can be placed multiple times but merged semantically, rust-analyzer shows them syntactically (unmerged) in the symbol tree.
