### ISSUE TITLE
nvim-lspconfig does not forward settings to the LSP

### ISSUE THREAD

**Issue by IvarWithoutBones** [oxalica/nil#25]
`nvim-lspconfig`'s nil module does not forward settings to the LSP, because of that it is currently impossible to configure the formatting command using it. This is a similar issue to #24.

I decided to file an issue here instead of upstream because their readme claims the configurations are unsupported, hope you don't mind.

I would also like to add that the link to the example configuration for `nvim-lspconfig` in the readme is broken, looks like that file got moved.

**Comment by oxalica** [comment]
It does work. I have an example setup for testing under `dev/`.

https://github.com/oxalica/nil/blob/68d9663f8eb556df8f5b4629614004f595e6af4e/dev/nvim-lsp.nix#L75-L84

You could set formatter command with the setting
```lua
      settings = {
        ['nil'] = {
          formatting = { command = { "nixpkgs-fmt" } }
        },
      },
```

**Comment by IvarWithoutBones** [comment]
Apologies, I configured it wrongly on my end then.

**Comment by will** [comment]
@oxalica thanks for posting the formatting config snippet above. I saw the docs saying "via LSP setting formatting.command" but couldn't figure out how to translate that into what lspconfig wanted. 

One thought, if `nixpkgs-fmt` is the most common formatter, maybe it should be the default if you don't give a particular configuration. If it's not present because it isn't currently installed, still don't error out or anything, but might save everyone having to configure a common thing?

Thanks for making this lsp server, I'm new to nix so it's extra useful for me :)

**Comment by figsoda** [comment]
https://github.com/NixOS/nix/pull/6087 added a `nix fmt` that's supposed to be the `blessed` way to format things, maybe that makes sense as a default

**Comment by will** [comment]
@oxalica thanks! Especially for the link to the rfcs, that's super handy.

**Comment by oxalica** [comment]
@figsoda 
> [NixOS/nix#6087](https://github.com/NixOS/nix/pull/6087) added a `nix fmt` that's supposed to be the "blessed" way to format things, maybe that makes sense as a default

That requires flake support, which is S.T.I.L.L. considered experimental. It's good to support it, but not as the default.
