### ISSUE TITLE
Comparison with `rnix-lsp`

### ISSUE THREAD

**Issue by hab25** [oxalica/nil#31]
Or at least describe what motivated the creation of `nil`, since comparisons are hard to keep up-to-date when both projects are under active development.

This should help users choose which one to use.

The [discourse announcement](https://discourse.nixos.org/t/nil-yet-another-language-server-for-nix/21843) has no mention of `rnix` either, but when reading
> aiming at better coding assistance

 one often wonders: better in what way(s)?

**Comment by Kranzes** [comment]
comparison: nil is better

**Comment by realsnick** [comment]
Unfortunately the contributor of rnix-lsp died via the repository readme comment

**Comment by hab25** [comment]
> Unfortunately the contributor of rnix-lsp died via the repository readme comment

Right, but others have commit access, and forking is, of course, possible

**Comment by oxalica** [comment]
As mentioned in README, there's a list of noticeable features in [`docs/features.md`](https://github.com/oxalica/nil/blob/bea40f71fc2b918ad6cf2154bcc12521ac664dc2/docs/features.md), if you want a comprehensive answer.

I used to playing with `rnix-lsp` for a short period of time, but it's more like a better-than-nothing basic tool and doesn't really improve my editing experience, plus some functions are simply incorrect (including the parser `rnix`, before I made some PRs). Its structure seems not scalable enough for more rich features ([`rust-analyzer`](https://github.com/rust-analyzer/rust-analyzer) for comparison), and it's not actively developing recently. Thus I try to recollect my ideas to make this project.

It's intentional to NOT put point-to-point comparison with other LSPs. It would be rather judged by you users.

**Comment by hab25** [comment]
> It's intentional to NOT put point-to-point comparison with other LSPs. It would be rather judged by you users.

@oxalica that's reasonable. I identified what you just shared as being largely anectodal (so I understand not wanting to call it "documentation"), but even so it does help me know what to look for when judging the pros/cons of both projects.

Maybe just having this issue exist is enough; people can find it with their search engines.

You can close if you want.

**Comment by hab25** [comment]
Correction here:
> I identified what you just shared as being largely anectodal

The feature list is comprehensive and not anecdotal.
