### ISSUE TITLE
Synatx highlighting is messed up

### ISSUE THREAD

**Issue by Kranzes** [oxalica/nil#49]
When enabling the nil with lspconfig on neovim the syntax highlighting looks like this now: 
![image](https://user-images.githubusercontent.com/56614642/210181017-89938fd9-ea46-4609-9900-11802247ab07.png)

When they should and used to look like this:
![image](https://user-images.githubusercontent.com/56614642/210181038-a62fdc7e-f6bf-4d1a-8f46-570048af9750.png)

I believe something got messed up in the past month or so. This also only happens with neovim nightly, with stable it looks fine. I tried changing nil to rnix-lsp and the colors seem fine.

**Comment by oxalica** [comment]
You could see that all attributes are grey, all variables are white, so it's probably switching to another colorscheme rather than "messed up".
I guess it's because neovim recently added semantic highlighting in https://github.com/neovim/neovim/pull/21100. The default colors of semantic highlightings are defined in [here](https://github.com/jdrouhard/neovim/blob/9f035559defd9d575f37fd825954610065d9cf96/src/nvim/highlight_group.c#L267) and you (or your colorscheme plugin) may want to customize them.
